# Generated by Django 3.2.8 on 2021-10-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makanan', models.TextField(blank=True, default='', null=True)),
                ('jenismakanan', models.CharField(max_length=20)),
                ('hargamakanan', models.IntegerField(blank=True, null=True)),
                ('minuman', models.TextField(blank=True, default='', null=True)),
                ('hargaminuman', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
